SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS address;
DROP TABLE IF EXISTS associated_service;
DROP TABLE IF EXISTS authorisation;
DROP TABLE IF EXISTS bid_status;
DROP TABLE IF EXISTS billing;
DROP TABLE IF EXISTS billing_type;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS professional;
DROP TABLE IF EXISTS request;
DROP TABLE IF EXISTS request_bid;
DROP TABLE IF EXISTS request_status;
DROP TABLE IF EXISTS request_subscription;
DROP TABLE IF EXISTS request_transaction;
DROP TABLE IF EXISTS security_question;
DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS subscription;
DROP TABLE IF EXISTS transaction;
DROP TABLE IF EXISTS transaction_status;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_question;

SET FOREIGN_KEY_CHECKS = 1;